[build]
command  = "pnpm run build"         # uses nuxi build --preset netlify
publish  = "dist"                   # <-- static assets

[functions]
# this path is where the preset outputs serverless bundles
directory = ".netlify/functions-internal"