import type { ModelEntry } from './types'

export const DEFAULT_MODEL_ID = 'gpt-5-mini-2025-08-07'

export const MODEL_REGISTRY: ModelEntry[] = [
  // ─── OpenAI (direct) ───
  {
    id: 'gpt-5.4-2026-03-05',
    label: 'GPT-5.4',
    provider: 'openai',
    routeType: 'direct',
    apiModel: 'gpt-5.4-2026-03-05',
    category: 'flagship',
    badges: ['Flagship', 'Vision'],
    capabilities: ['text', 'vision', 'tools', 'reasoning', 'code'],
    enabled: true,
    featured: true,
    pricingHint: '$$$',
    speedHint: 'medium',
    contextWindow: 128000,
  },
  {
    id: 'gpt-5-mini-2025-08-07',
    label: 'GPT-5 Mini',
    provider: 'openai',
    routeType: 'direct',
    apiModel: 'gpt-5-mini-2025-08-07',
    category: 'fast',
    badges: ['Fast', 'Vision'],
    capabilities: ['text', 'vision', 'tools', 'code'],
    enabled: true,
    featured: true,
    pricingHint: '$',
    speedHint: 'fast',
    contextWindow: 128000,
  },

  // ─── Anthropic (direct) ───
  {
    id: 'claude-opus-4-6',
    label: 'Claude Opus 4',
    provider: 'anthropic',
    routeType: 'direct',
    apiModel: 'claude-opus-4-6',
    category: 'flagship',
    badges: ['Flagship', 'Reasoning'],
    capabilities: ['text', 'vision', 'tools', 'reasoning', 'code', 'pdf'],
    enabled: true,
    featured: true,
    pricingHint: '$$$',
    speedHint: 'slow',
    contextWindow: 200000,
  },
  {
    id: 'claude-sonnet-4-6',
    label: 'Claude Sonnet 4',
    provider: 'anthropic',
    routeType: 'direct',
    apiModel: 'claude-sonnet-4-6',
    category: 'flagship',
    badges: ['Flagship', 'Vision'],
    capabilities: ['text', 'vision', 'tools', 'reasoning', 'code', 'pdf'],
    enabled: true,
    featured: true,
    pricingHint: '$$',
    speedHint: 'medium',
    contextWindow: 200000,
  },
  {
    id: 'claude-3-5-sonnet-latest',
    label: 'Claude 3.5 Sonnet',
    provider: 'anthropic',
    routeType: 'direct',
    apiModel: 'claude-3-5-sonnet-latest',
    category: 'fast',
    badges: ['Fast', 'Vision'],
    capabilities: ['text', 'vision', 'tools', 'code', 'pdf'],
    enabled: true,
    featured: false,
    pricingHint: '$$',
    speedHint: 'fast',
    contextWindow: 200000,
  },

  // ─── Google Gemini (direct) ───
  {
    id: 'gemini-3.1-pro-preview',
    label: 'Gemini 3.1 Pro',
    provider: 'google',
    routeType: 'direct',
    apiModel: 'gemini-3.1-pro-preview',
    category: 'flagship',
    badges: ['Flagship', 'Vision'],
    capabilities: ['text', 'vision', 'reasoning', 'code', 'pdf'],
    enabled: true,
    featured: true,
    pricingHint: '$$',
    speedHint: 'medium',
    contextWindow: 1000000,
  },
  {
    id: 'gemini-3-flash-preview',
    label: 'Gemini 3 Flash',
    provider: 'google',
    routeType: 'direct',
    apiModel: 'gemini-3-flash-preview',
    category: 'fast',
    badges: ['Fast', 'Vision'],
    capabilities: ['text', 'vision', 'code', 'pdf'],
    enabled: true,
    featured: true,
    pricingHint: '$',
    speedHint: 'fast',
    contextWindow: 1000000,
  },
  {
    id: 'gemini-3.1-flash-lite-preview',
    label: 'Gemini 3.1 Flash-Lite',
    provider: 'google',
    routeType: 'direct',
    apiModel: 'gemini-3.1-flash-lite-preview',
    category: 'budget',
    badges: ['Cheap', 'Fast'],
    capabilities: ['text', 'vision', 'pdf'],
    enabled: true,
    featured: false,
    pricingHint: '$',
    speedHint: 'fast',
    contextWindow: 1000000,
  },

  // ─── Groq (direct) ───
  {
    id: 'llama-3.1-70b-versatile',
    label: 'Llama 3.1 70B',
    provider: 'groq',
    routeType: 'direct',
    apiModel: 'llama-3.1-70b-versatile',
    category: 'open',
    badges: ['Open', 'Fast'],
    capabilities: ['text', 'code'],
    enabled: true,
    featured: true,
    pricingHint: '$',
    speedHint: 'fast',
    contextWindow: 131072,
  },

  // ─── OpenRouter expansion (disabled by default) ───
  {
    id: 'openrouter/deepseek/deepseek-r1',
    label: 'DeepSeek R1',
    provider: 'openrouter',
    routeType: 'openrouter',
    apiModel: 'deepseek/deepseek-r1',
    category: 'flagship',
    badges: ['Reasoning', 'Open'],
    capabilities: ['text', 'reasoning', 'code'],
    enabled: false,
    featured: false,
    pricingHint: '$',
    speedHint: 'medium',
    contextWindow: 64000,
  },
  {
    id: 'openrouter/meta-llama/llama-4-maverick',
    label: 'Llama 4 Maverick',
    provider: 'openrouter',
    routeType: 'openrouter',
    apiModel: 'meta-llama/llama-4-maverick',
    category: 'open',
    badges: ['Open', 'Vision'],
    capabilities: ['text', 'vision', 'code'],
    enabled: false,
    featured: false,
    pricingHint: '$$',
    speedHint: 'medium',
    contextWindow: 1048576,
  },
  {
    id: 'openrouter/mistralai/mistral-large-2',
    label: 'Mistral Large 2',
    provider: 'openrouter',
    routeType: 'openrouter',
    apiModel: 'mistralai/mistral-large-2',
    category: 'flagship',
    badges: ['Flagship'],
    capabilities: ['text', 'tools', 'code'],
    enabled: false,
    featured: false,
    pricingHint: '$$',
    speedHint: 'medium',
    contextWindow: 128000,
  },
  {
    id: 'openrouter/qwen/qwen-2.5-72b-instruct',
    label: 'Qwen 2.5 72B',
    provider: 'openrouter',
    routeType: 'openrouter',
    apiModel: 'qwen/qwen-2.5-72b-instruct',
    category: 'open',
    badges: ['Open'],
    capabilities: ['text', 'code'],
    enabled: false,
    featured: false,
    pricingHint: '$',
    speedHint: 'medium',
    contextWindow: 131072,
  },
]
